Script started on Thu 01 Aug 2024 09:35:40 PM EDT
==192882== Memcheck, a memory error detector
==192882== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==192882== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==192882== Command: ws data_int.bin data_int_target.bin
==192882== 
[38;5;9mBegin Testing the Program!
--------------------------[0m

Command Line:
--------------------------
  1: ws
  2: data_int.bin
  3: data_int_target.bin
--------------------------

==========================================================================================
                   Average and variance of record-values using 1 thread
------------------------------------------------------------------------------------------
Item's count in file 'data_int.bin': 0
==192882== Invalid read of size 4
==192882==    at 0x4039D3: seneca::ProcessData::ProcessData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) (ProcessData.cpp:63)
==192882==    by 0x40217C: main (w9_p2_prof.cpp:70)
==192882==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==192882== 
==192882== 
==192882== Process terminating with default action of signal 11 (SIGSEGV)
==192882==  Access not within mapped region at address 0x0
==192882==    at 0x4039D3: seneca::ProcessData::ProcessData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) (ProcessData.cpp:63)
==192882==    by 0x40217C: main (w9_p2_prof.cpp:70)
==192882==  If you believe this happened as a result of a stack
==192882==  overflow in your program's main thread (unlikely but
==192882==  possible), you can try to increase the size of the
==192882==  main thread stack using the --main-stacksize= flag.
==192882==  The main thread stack size used in this run was 8388608.
==192882== 
==192882== HEAP SUMMARY:
==192882==     in use at exit: 73,748 bytes in 2 blocks
==192882==   total heap usage: 3 allocs, 1 frees, 73,801 bytes allocated
==192882== 
==192882== 20 bytes in 1 blocks are still reachable in loss record 1 of 2
==192882==    at 0x4C2B87D: operator new(unsigned long) (vg_replace_malloc.c:472)
==192882==    by 0x4035D7: void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) (basic_string.tcc:225)
==192882==    by 0x40341A: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&) (basic_string.h:639)
==192882==    by 0x40206C: main (w9_p2_prof.cpp:29)
==192882== 
==192882== 73,728 bytes in 1 blocks are still reachable in loss record 2 of 2
==192882==    at 0x4C2B15C: malloc (vg_replace_malloc.c:431)
==192882==    by 0x4EE72CD: pool (eh_alloc.cc:235)
==192882==    by 0x4EE72CD: __static_initialization_and_destruction_0 (eh_alloc.cc:373)
==192882==    by 0x4EE72CD: _GLOBAL__sub_I_eh_alloc.cc (eh_alloc.cc:456)
==192882==    by 0x400F9C2: _dl_init (in /usr/lib64/ld-2.17.so)
==192882==    by 0x4001179: ??? (in /usr/lib64/ld-2.17.so)
==192882==    by 0x2: ???
==192882==    by 0x1FFF0001DA: ???
==192882==    by 0x1FFF0001DD: ???
==192882==    by 0x1FFF0001EA: ???
==192882== 
==192882== LEAK SUMMARY:
==192882==    definitely lost: 0 bytes in 0 blocks
==192882==    indirectly lost: 0 bytes in 0 blocks
==192882==      possibly lost: 0 bytes in 0 blocks
==192882==    still reachable: 73,748 bytes in 2 blocks
==192882==         suppressed: 0 bytes in 0 blocks
==192882== 
==192882== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==192882== 
==192882== 1 errors in context 1 of 1:
==192882== Invalid read of size 4
==192882==    at 0x4039D3: seneca::ProcessData::ProcessData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) (ProcessData.cpp:63)
==192882==    by 0x40217C: main (w9_p2_prof.cpp:70)
==192882==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==192882== 
==192882== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
bash: line 1: 192882 Segmentation fault      /usr/local/valgrind-3.21.0/bin/valgrind --show-error-list=yes --leak-check=full --show-leak-kinds=all --track-origins=yes ws data_int.bin data_int_target.bin

Script done on Thu 01 Aug 2024 09:35:42 PM EDT
